### ISSUE TITLE
KeyError: 'musicImmersiveHeaderRenderer'

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [sigma67/ytmusicapi#117]
When calling `get_artist()` with `browseId` received from `get_library_artists()` I get
`KeyError: 'musicImmersiveHeaderRenderer'`.
If I call `get_artist()` with channelId from the browser, it works as intended.

Here's the traceback:
```
Traceback (most recent call last):
  File "/home/ozymandias/Projects/mopidy/.venv/lib/python3.8/site-packages/mopidy_ytmusic/backend.py", line 487, in browse
    res = API.get_artist(id_)
  File "/home/ozymandias/Projects/mopidy/.venv/lib/python3.8/site-packages/ytmusicapi/mixins/browsing.py", line 206, in get_artist
    header = response['header']['musicImmersiveHeaderRenderer']
KeyError: 'musicImmersiveHeaderRenderer'
```

**Comment by sigma67** [comment]
This is due to a recent YouTube update. When you click on an artist in your library, you are now shown the artist's songs in your library, with another link pointing to the actual artist. This endpoint is not yet implemented in ytmusicapi.

The browseId used for this new page is in the following format: `MPLA` + `channelId`. So if you simply remove those first 4 letters, you should be able to use `get_artist `with the browseId returned by `get_library_artists`.
