### ISSUE TITLE
[Question] get stream url for track

### ISSUE THREAD

**Issue by AndreasWidmer** [sigma67/ytmusicapi#13]
Hi,

thanks for your time creating this script.
Can you tell if there is a possibility to get the streaming url for a track like the gmusicapi did?

Greetings,
Andreas

**Comment by sigma67** [comment]
Hey, this is currently not implemented. 

Every song/video on YouTube Music is essentially a YouTube video. Most of this project uses the API music.youtube.com, however when you press 'Play' in YouTube Music, it uses the regular YouTube endpoints.  I think the endpoint https://www.youtube.com/get_video_info is used to get video streaming data. Therefore I think getting a streaming URL might be out of scope for this API, since there's many existing APIs for dealing with YouTube videos.

For example, you should be able to use `youtube-dl` to download the song. There's a [sample implementation in tombulled's project](https://github.com/tombulled/python-youtube-music/blob/master/ytm/apis/YouTubeMusicDL/__init__.py).

**Comment by AndreasWidmer** [comment]
Ah, i see.
Thanks for the clarification and help :)

Thank you & keep up the good work!
