### ISSUE TITLE
[Question] Client in other languages

### ISSUE THREAD

**Issue by gelouko** [sigma67/ytmusicapi#137]
Hello,

I just wanted to know if there is any intention to make this repo language-agnostic (or at least generate a JavaScript client for the YTMusic API.

Are there any plans for that?
Or the scope of the project is just for Python?

Thanks!

**Comment by gelouko** [comment]
NVM, just found this
https://github.com/emresenyuva/youtube-music-api#readme

**Comment by sigma67** [comment]
Yes, there are some projects for other languages. Although I'm not aware of one that also provides authenticated functionality (library,uploads etc). 

I don' have any plans for this project to branch out, but I'm open to others using this project's code to develop something similar in other languages. JS would be an obvious candidate since it works with browsers
