### ISSUE TITLE
Passing a playlist id to get_watch_playlist gives an exception

### ISSUE THREAD

**Issue by JBBgameich** [sigma67/ytmusicapi#179]
Albums and tracks work just fine with get_watch_playlist, but playlists don't (if I'm not doing something wrong).

Ther error is:
```
KeyError: 'content'

At:
  /usr/local/lib/python3.9/dist-packages/ytmusicapi/parsers/utils.py(210): nav
  /usr/local/lib/python3.9/dist-packages/ytmusicapi/mixins/watch.py(78): get_watch_playlist
```

A simple test case:
```
import ytmusicapi
yt = ytmusicapi.YTMusic()
yt.get_watch_playlist("VLPLMOhiB5NIEx7us1pGnMZXGcN6dSL45uZu")
```

**Comment by sigma67** [comment]
You need to call it like this 

`yt.get_watch_playlist(playlistId="PLMOhiB5NIEx7us1pGnMZXGcN6dSL45uZu")

**Comment by JBBgameich** [comment]
Sorry, I messed up the test case. The error still occurs with
```
yt.get_watch_playlist(playlistId="VLPLMOhiB5NIEx7us1pGnMZXGcN6dSL45uZu")
```
too

**Comment by JBBgameich** [comment]
I must have messed up the playlist id too, thank you for the help.

**Comment by JBBgameich** [comment]
Just in case someone finds this useful: I don't really understand why, but it is necessary to remove the "VL" from the beginning of the playlist IDs.

**Comment by sigma67** [comment]
Yes, that's why I removed the VL in my comment above.

YouTube sometimes uses the VL prefix internally. I think it's mainly a prefix to differentiate actual playlists from radio playlists and others. Some other endpoints like get_playlist can already handle the VL prefix, I suppose we could add something to `get_watch_playlist_ as well.
