### ISSUE TITLE
get_playlist limit not working

### ISSUE THREAD

**Issue by Keldraistaken** [sigma67/ytmusicapi#190]
![image](https://user-images.githubusercontent.com/45337750/115243907-15203f80-a12c-11eb-9bb2-c02289d94523.png)

![image](https://user-images.githubusercontent.com/45337750/115243868-0b96d780-a12c-11eb-93b6-46476174e3cf.png)

am i dumb

**Comment by sigma67** [comment]
It works just like the YouTube Music website. You can't retrieve less than 100 playlist items. Since ytmusicapi has to fetch the data anyway, it just returns all of it. This is consistent across the whole API, you will always get increments of the default limit (100 for playlists). If it's a different number, it's because the playlist has less than 100 items total, or because some library endpoints are flaky and sometimes don't return all songs
