### ISSUE TITLE
Unable to get correct videoId of the song

### ISSUE THREAD

**Issue by YashMakan** [sigma67/ytmusicapi#203]
For some songs, I am not getting the correct videoId. When I tried to search for the videoId on youtube it says that the video is not available. Even I am not able to install the video with youtube-dl, pafy etc. 
For example, I searched for "blank space" song by Taylor swift using `ytmusic.search('blank space')`  and it return `V1mzLYKb35I` id. Now If I search https://www.youtube.com/watch?v=V1mzLYKb35I it shows that the video is not available. 
Also when I search "blank space" on youtube music and the id is different from the API. I am using v0.17.3

**Comment by sigma67** [comment]
Not sure what the problem is? The videoId is being returned by ytmusicapi. Of course the song is unavailable, which means you won't be able to download it.

It probably doesn't show up in the web interface because unavailable songs are hidden there sometimes (not everything in the API response is shown on the interface).
