### ISSUE TITLE
Wrong sorting in search results

### ISSUE THREAD

**Issue by SirLyoshyk** [sigma67/ytmusicapi#277]
Hello!
I'm getting wrong sorting in results using ytmusicapi 0.22.0

Code:
`youtubeMusicApiClient = YTMusic('headers_auth.json')`
`search_results = youtubeMusicApiClient.search('Polly Bergen - Come Prima', 'songs')`

In API results songs are sorted in different way rather then in browser (you can easily see it comparing albums):
http://i.imgur.com/7rh1uBl.png
http://i.imgur.com/TXrOSmq.png

Here you can see all api results:
https://pastebin.com/J7KAsBPV

Can it be fixed?

Thank you.

**Comment by sigma67** [comment]
ytmusicapi always returns results in the exact same order they are provided by the server. I assume your requests are different, for example because you are not signed in in the browser, but are signed in in ytmusicapi. Else you may be using different accounts or accounts languages, or something else like connecting through a proxy from a different country. Either way, something is causing the server to return a different order.

**Comment by SirLyoshyk** [comment]
@sigma67 If I used headers from my browsers for API setup, so API must use the same account, same language and etc...
How I can check if request from browser and request from API are the same?

**Comment by sigma67** [comment]
Are you using the same brand account (top right icon)? Are you using some kind of browser plugin that modifies the request that does not apply in Python? Else they should be the same
