### ISSUE TITLE
Support additional languages

### ISSUE THREAD

**Issue by kidmil** [sigma67/ytmusicapi#29]
hi
i use this ytmapi.
it's very good api.
but i have some problem about language. 
it returns not korean music title or artist name but english music title or artist name.

can i get other langauge's music info not english?

ah.. i use get_history method.

**Comment by sigma67** [comment]
Hey, the language is currently fixed to English and specified in the library's `context.json` (hl variable). 

Supporting multiple languages will require some significant testing, as some string parsing may break due to different encodings. For example, I tested get_playlist with hl='de' and it required adding `unicodedata.normalize` to the function. Feel free to experiment with different languages (i.e. korean) and let me know what you find.
