### ISSUE TITLE
how to get 'songs' and not music video when using get_album()

### ISSUE THREAD

**Issue by Mohammad9760** [sigma67/ytmusicapi#333]
hey there!
so I can filter the search() to return only 'songs' and not music videos but when I use get_album()['tracks'] the videoId is the link to the music videos if there's a music video for that song.
how do I get the tracks of an album as 'songs', the only way I can think of is to get the track name and artist name and do a search() again with 'songs' filter but that's too tricky and not good for my performance.
thanks!

**Comment by sigma67** [comment]
Use an authenticated instance: https://ytmusicapi.readthedocs.io/en/stable/setup.html

Non-authenticated requests usually return mostly music videos.

**Comment by RaduTek** [comment]
Here is my workaround for this [https://github.com/RaduTek/YTMusicDL/blob/master/ytmusicdl.py#L859](https://github.com/RaduTek/YTMusicDL/blob/master/ytmusicdl.py#L859)

Basically I use yt-dlp to get the playlist with the ID from audioPlaylistId, as on regular YouTube those playlists seem to always list the audio/album version. Then I try and match the song from the YT Music album with the one from the YT playlist by the index number.

It is an annoying workaround you have to do for unauthenticated **and free** accounts, since audio only mode is a YT Music Premium feature.
