### ISSUE TITLE
Help needed understanding videoType values from get_playlist()

### ISSUE THREAD

**Issue by MarkhorDev** [sigma67/ytmusicapi#353]
I am using v0.25.0.

I am trying to distinguish between actual songs on YTM and youtube videos that are playable on YTM. In the data returned by get_playlist(), in the tracks, each entry has a "videoType" item, with values such as "MUSIC_VIDEO_TYPE_ATC", "MUSIC_VIDEO_TYPE_ATV", "MUSIC_VIDEO_TYPE_OMV", etc.

I am trying to understand what each of these values represents. Looking at the source code, it seems these values aren't defined by you and instead come from YTM, but I was wondering if you have any understanding of what they mean. I have looked at the YouTube Data API but can't find anything. Any help is appreciated

**Comment by sigma67** [comment]
Related: https://github.com/sigma67/ytmusicapi/pull/265

Best guess:
- OMV: Original Music Video - uploaded by original artist with actual video content
- UGC: User Generated Content - uploaded by regular YouTube user
- ATV: Artist ... - uploaded by original artist with cover image only
- ATC: never seen this

Might be a good addition to the FAQ.

**Comment by Zombee8424** [comment]
I may have misread one of the values because I cannot find ATC anywhere.

OMV does seem to be that, although I think while some songs which have a video attached are showing as OMV, some are not. I will look into this.

I also do not have any guesses as to what ATV stands for.

I also ran into MUSIC_VIDEO_TYPE_OFFICIAL_SOURCE_MUSIC for videos like [this](https://youtu.be/HT4S7lTmzVU). I guess this is for videos which are official video content, but not for a single track.

And both uploaded songs, and invalid songs (i.e videos that cannot be played in YTM but are in a playlist with songs, and songs/videos which have been removed) both have None as their video type. It may be useful to have a value for these which distinguishes the two if this is possible.
