### ISSUE TITLE
search: top result category not working

### ISSUE THREAD

**Issue by Elmar1991** [sigma67/ytmusicapi#360]
Hello, some data that has been changed in music youtube is not working correctly.

**Comment by kattums** [comment]
Hey, I'm having a similar problem where it looks like something has changed with the YouTube Music API.

I was previously using `YTMusic.search()` passing a `track_id` as my query, which would return an array containing the results objects (I use `search()` rather than `get_song()` because it returns additional information that `get_song()` doesn't have). Now, calling `YTMusic.search(track_id)` returns an empty array. I discovered that appending a filter param fixes this behaviour. `YTMusic.search(track_id, filter='songs')` returns the same results I had previously.

Maybe this is of help to you.

**Comment by Elmar1991** [comment]
> Hey, I'm having a similar problem where it looks like something has changed with the YouTube Music API.
> 
> I was previously using `YTMusic.search()` passing a `track_id` as my query, which would return an array containing the results objects (I use `search()` rather than `get_song()` because it returns additional information that `get_song()` doesn't have). Now, calling `YTMusic.search(track_id)` returns an empty array. I discovered that appending a filter param fixes this behaviour. `YTMusic.search(track_id, filter='songs')` returns the same results I had previously.
> 
> Maybe this is of help to you.

It's not about what you say. I am saying it is a problem again, please help this.@sigma67

**Comment by Elmar1991** [comment]
``

> Everything works fine here. Please add more details and a code sample if you need help with something.

`from ytmusicapi import YTMusic

ytmusic = YTMusic()
search = ytmusic.search('Taylor+Swift+Blank+Space', filter='songs')
print(search);`

When `filter = 'songs'` it appears in videos between songs as a result

There were some changes on the https://music.youtube.com site 1 day ago, please take this into consideration.

**Comment by Elmar1991** [comment]
i tested it and i write here what is not working correctly,
1.) Top result not working.
2.) When searching, the correct results do not come when there is a limit of more than 20. @sigma67

**Comment by sigma67** [comment]
There have been multiple issues on `search` without filters, but I haven't seen them on my end yet. You can only get more than 20 results if using filters. 

Top result format seems to have changed, so that may indeed be a bug.

**Comment by Elmar1991** [comment]
yes it works thank you. @sigma67
