### ISSUE TITLE
`get_artist` audiobooks and shows support

### ISSUE THREAD

**Issue by H3adsho0ot** [sigma67/ytmusicapi#460]
If i browse an artist having audiobooks those are not shown in the result. I thik they should be shown as albums. 

(https://music.youtube.com/browse/MPADUCf2vTMnvFb8BsWTWauTZrow) <- example

If I execute yt.get_artist('UCyiY-0Af0O6emoI3YvCEDaA') I get two singles but no albums or playlist or anything else.

Thanks in advance
Niklas

**Comment by sigma67** [comment]
Sorta related to #415 , need to update some functions to keep up with the content expansion in YTMusic

**Comment by sigma67** [comment]
That works for English only but needs to be localized to all supported languages

**Comment by sigma67** [comment]
Should support two new categories for the artists page:

https://music.youtube.com/channel/UCf2vTMnvFb8BsWTWauTZrow

- Shows and audiobooks - localized
- Details page: new function `get_artist_shows`

https://music.youtube.com/channel/UCKPSmMfDsXTKrCZApukcJ7A

- Latest episodes - localized
- Details page: new function `get_artist_episodes`

**Comment by MarkhorDev** [comment]
Recently commented on another issue but was pointed here. When calling 'get_artist' for an artist with podcasts on their page, a KeyError is raised. For example, the [first video](https://music.youtube.com/podcast/s0ApKrZPcak) on [this](https://music.youtube.com/channel/UCD14H15GYNnPRmAwkTnlPHg) page is marked as a podcast episode, for some unknown reason. Calling 'get_artist' with this artist ID results in a 'KeyError: 'watchEndpoint'' being raised. I do not know why this happens besides because of the podcast episode.
