### ISSUE TITLE
get_artist returns different channelId for some artists

### ISSUE THREAD

**Issue by Schtenk** [sigma67/ytmusicapi#480]
You missunderstand me in both #477 and #479.
What im saying is and that the channelId parsed from the get_artist response is the wrong one so if used again in with get_artist no songs are returned, as the links clearly shows.

sorry for trying to help, I wont make more issues.

**Comment by sigma67** [comment]
You know you can just reopen the issue or comment below. This is just being obnoxious.

If you followed the issue template it would be much easier to reproduce your issue. Here it is again:

# Hello and thanks for using ytmusicapi! Please fill out the issue template below. Issues not following this template will be closed without comment. If you have a question only, please use GitHub discussions or gitter (linked in README).
~~~~~~~~~~~~~
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Additional context**
Add any other context about the problem here, such as a code sample.

**Comment by sigma67** [comment]
I mean yes, I guess this is a valid issue.

On the other hand, when you're calling `get_artist` you already have the `channelBrowseId`. So isn't it more useful to return the `channelId` from the subscribeButton in that case?

**Comment by Schtenk** [comment]
Sure, may just be a naming/documentation issue where both are called channelId. It should rarely be a problem but if a user saves the subscribe one for later thinking they are the same, may then lead to the issue occuring.

**Comment by sigma67** [comment]
Renaming the key is difficult since it would break backwards compatibility. In light of this `subscriptionChannelId` would be the better name. I think we can add it to the docstring?
