### ISSUE TITLE
[Question] How to add/remove library content

### ISSUE THREAD

**Issue by tadly** [sigma67/ytmusicapi#68]
The README stats _add/remove library content_ but from reading the tests and the source I can't figure out how to do this.
Is this not yet implemented or is the library a "playlist" with a special id or something?

Thanks for the help

**Comment by sigma67** [comment]
The library refers to anything that's personalized to the user, such as playlists, songs/artists/albums in the personal library, account history, etc. See here: 

- https://music.youtube.com/library/
- https://ytmusicapi.readthedocs.io/en/latest/reference.html#library

**Comment by tadly** [comment]
Oooooh `YTMusic.rate_playlist` is what I want I think.
Google always implements the weirdest backends :/

Sorry for the noise and thanks for the quick reply :)

**Comment by apastel** [comment]
So, I have the same question as OP. But it seems like OP decided he/she didn't want to add library content after all...

I don't see a function for adding particular songs/albums to your library. Is that currently possible with the API?

**Comment by sigma67** [comment]
For songs, use `rate_song` to like them. For albums, use `rate_playlist`. Either will add the item to your library.

**Comment by apastel** [comment]
Ah, ok now I understand why OP said that.
It's weird that rating and adding/removing are coupled like that (what if I want to add a song and not have it be 'liked'?) but I imagine that wasn't an implementation decision you made, but more of a backend limitation like OP said.

I know it's been said already but thanks for implementing this. I'm using it to delete all uploads since there's no button for that yet: https://github.com/apastel/ytmusic-deleter

**Comment by sigma67** [comment]
It's entirely the YT backend. All this API does is emulate requests that happen on the web interface. Essentially I look at what happens when you press a button there and emulate that call in Python.

Regarding the rating = adding to library, I suppose it has to do with the way they do recommendations. You can also dislike albums and playlists with the API, one of the few things that isn't possible in the web interface (that I know of). This affects your recommendations.

**Comment by phirestalker** [comment]
Either something is wrong on my end or I don't understand something.
I have used the API to like songs. When I go into the web interface it is in liked songs, but not all of them end up in the library. By this, I mean that the right-click menu still has the option "add to library."
Does this mean what I understand as add to library in the context of this API and thread question is different?
Did they recently change how they do things?
Also, I looked at the request in Firefox after I press "add to library" on a song, and instead of making a call to /youtubei/v1/like/like? (like it does for a thumbs up), it makes a call to /youtubei/v1/feedback. So, there seems to be something separate going on in the background.

**Comment by sigma67** [comment]
I believe they should still be added to your library if you like them. I just tried and after liking, it didn't show up in "Recently added" library, but when sorting by A-Z it showed up.

And I don't think you are able to add individual songs to the library? At least there's no option in the context menu.

**Comment by phirestalker** [comment]
Could it be different for me because I have a subscription? I'm not sure
but it definitely has an add to library option on most songs in the context
menu. It doesn't show up on some songs though.

**Comment by sigma67** [comment]
No, I also have a subscription. On second thought the song I mentioned above was probably already in my library since I added its album sometime ago. 

Checking other songs I also saw that there is an "Add to library" button on the ones not already in the library. It only seems to apply to actual songs, not YouTube videos of songs. Might need an additional function for the case of adding a song to the library via the `feedback` endpoint.

**Comment by sigma67** [comment]
Thanks again for the heads up @phirestalker , I hope it is implemented properly now.

**Comment by phirestalker** [comment]
No problem, it confused me at first because liking something really SHOULD add it to the library. This is another example of Google's haphazard programming and planning.
I will be testing it out today or tomorrow as I am trying to perfect my script that scans my music files and matches them to their twin in Youtube music and uploads them if they are not found.

**Comment by phirestalker** [comment]
Yes, it works great. Thanks.

**Comment by phirestalker** [comment]
It seems that feedbackTokens is missing from tracks returned from get_liked_songs.

**Comment by phirestalker** [comment]
Sorry forgot the info.

```
{'videoId': '7ysFgElQtjI', 'title': 'Old Town Road (feat. Billy Ray Cyrus)', 'artists': [{'name': 'Lil Nas X', 'id': 'UCCF_6PwrZf1u70yghKms3Mw'}], 'album': None, 'likeStatus': 'LIKE', 'thumbnails': [{'url': 'https://i.ytimg.com/vi/7ysFgElQtjI/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3mgzzB0Z27bC1TD426pgGsigXeJCA', 'width': 400, 'height': 225}], 'isAvailable': True, 'duration': '2:38'}
Adding song "Old Town Road (feat. Billy Ray Cyrus)" by Lil Nas X: 2:38
Traceback (most recent call last):
  File "ytmusic-sync/./sync.py", line 211, in <module>
    ytmusic.edit_song_library_status(song['feedbackTokens']['add'])
KeyError: 'feedbackTokens'
```

**Comment by sigma67** [comment]
It will not appear on YouTube videos. Only songs that are "proper" songs within YouTube Music. Usually you can tell the difference by looking at the artist name or if they have an album.

**Comment by phirestalker** [comment]
Until I clear my likes of videos, what is the best way to determine if a "song" on a playlist is actually a video? How does the search function tell? The only thing I can see from the data returned by get_liked_songs is that there is no album.
Have you seen actual songs that do not have an album name?

**Comment by phirestalker** [comment]
Oh, I see. I will just skip those then. Thanks.
