### ISSUE TITLE
1.9.0: ytmusicapi oauth results in "ValueError: relative path can't be expressed as a file URI"

### ISSUE THREAD

**Issue by sandrotosi** [sigma67/ytmusicapi#699]
**Describe the bug**

```
$ ytmusicapi oauth
Traceback (most recent call last):
  File "venv/bin/ytmusicapi", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "venv/lib/python3.11/site-packages/ytmusicapi/setup.py", line 78, in main
    print(f"Creating {Path(filename).as_uri()} with your authentication credentials...")
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 567, in as_uri
    raise ValueError("relative path can't be expressed as a file URI")
ValueError: relative path can't be expressed as a file URI
```

**To Reproduce**

run the code above in python3.11 or a small reproducer:

```
>>> from pathlib import Path
>>> Path('oauth.json').as_uri()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/pathlib.py", line 567, in as_uri
    raise ValueError("relative path can't be expressed as a file URI")
ValueError: relative path can't be expressed as a file URI
```

which is what's done in https://github.com/sigma67/ytmusicapi/blob/main/ytmusicapi/setup.py#L77-L78

**Comment by ImpenetrableNoble** [comment]
@sandrotosi Yeah I had that error before it doesn't surprise me, because the `as_uri()` method in Python's `pathlib` module requires an absolute path to convert it into a URI, but you’re providing a relative path like `'oauth.json'`. If you want to fix it, you can resolve the relative path to an absolute path using `Path('oauth.json').resolve()` before calling `as_uri()`, or you can ensure the script runs in the correct working directory where the file is located. 

You could modify the `ytmusicapi` library’s code to resolve the path before converting it to a URI, or check the library’s documentation for specific setup instructions. If the issue is related to Python 3.11, you might also try running the code in an earlier version of Python.
