### ISSUE TITLE
No way to tell explicit and non explicit versions of songs apart?

### ISSUE THREAD

**Issue by kubeckubis44** [sigma67/ytmusicapi#99]
Hi!
I was wondering if there is a way to tell if a song is explicit (they have that small 'E' tag in front of the track name) or not.
I could'nt find anything about it in the metadata returned by `get_song` and i think it would be a very useful thing to include there (if possible).

**Comment by sigma67** [comment]
It's not possible with get_song unfortunately, since that uses a YouTube endpoint that does not mark explicit songs. For albums it is possible using the contentRating property. For playlists it should be possible, but the data is inconsistent and I can't really figure out which property indicates that a song is explicit.

So it would have to be done for each endpoint separately. Which one would you use it for? Pull requests are welcome as always.

**Comment by sigma67** [comment]
I figured out why explicit songs seemed inconsistent: Some songs are only marked as explicit when signed in. Will add an `explicit` property for applicable endpoints with the next version.
